'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BLOrdenVenta.vb
''  Implementation of the Class BLOrdenVenta
''  Generated by Enterprise Architect
''  Created on:      04-Jun-2014 11:19:05 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


Public Class BLOrdenVenta


    ''' 
    ''' <param name="oOV"></param>
    Public Function Actualizar(ByVal oOV As BE.BEOrdenVenta) As Boolean
        Actualizar = False
    End Function

    ''' 
    ''' <param name="oOV"></param>
    Public Function Crear(ByVal oOV As BE.BEOrdenVenta) As Boolean
        Dim res As Boolean = True
        Try
            Dim oDal As DAL.DALOrdenVenta = New DAL.DALOrdenVenta()
            oDal.Crear(oOV)

        Catch ex As Exception
            Throw New ExceptionsPersonales.CustomException("ErrCrearOV")
        End Try

        Return res

    End Function

    ''' 
    ''' <param name="oOV"></param>
    Public Function FiltrarMes(ByVal oOV As BE.BEOrdenVenta) As List(Of BE.BEOrdenVenta)
        Dim lista As List(Of BE.BEOrdenVenta) = New List(Of BE.BEOrdenVenta)
        Try
            Dim oDAL As DAL.DALOrdenVenta = New DAL.DALOrdenVenta
            lista = oDAL.FiltrarMes(oOV)

            Return lista
        Catch ex As Exception
            Throw ex
        Finally
            lista = Nothing
        End Try
        'Return lista
    End Function


    ''' 
    ''' <param name="oOV"></param>
    Public Function Filtrar(ByVal oOV As BE.BEOrdenVenta) As List(Of BE.BEOrdenVenta)
        Dim lista As List(Of BE.BEOrdenVenta) = New List(Of BE.BEOrdenVenta)
        Try
            Dim oDAL As DAL.DALOrdenVenta = New DAL.DALOrdenVenta
            lista = oDAL.Filtrar(oOV)

            Return lista
        Catch ex As Exception
            Throw ex
        Finally
            lista = Nothing
        End Try
        'Return lista
    End Function


End Class ' BLOrdenVenta

