'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEBackupService.vb
''  Implementation of the Class BEBackupService
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:48:08 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Public Class BEBackupService
    Inherits BEServicioAdicional
    Sub New()
        Id = 4
    End Sub
End Class ' BEBackupService
