'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BECloudServer.vb
''  Implementation of the Class BECloudServer
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:47:23 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Public MustInherit Class BECloudServer
    Inherits BE.BEServicioBase

    Friend _srv_adicionales As List(Of BEServicioAdicional) = New List(Of BEServicioAdicional)

    Public ReadOnly Property Srv_adicionales() As List(Of BEServicioAdicional)
        Get
            Return _srv_adicionales
        End Get
        'Set(ByVal Value As List(Of BEServicioAdicional))
        '    _srv_adicionales = Value
        'End Set
    End Property

    Public MustOverride Sub addAdicional(ByVal addon As BE.BEServicioAdicional)


End Class ' BECloudServer

