'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEFamilia.vb
''  Implementation of the Class BEFamilia
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:31:05 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



'Option Explicit On
'Option Strict On



Public Class BEFamilia
    Inherits BE.BEPatenteBasica


    Private _patentes As List(Of BEPatenteBasica)
    Public m_BEPatenteBasica As BEPatenteBasica

    Public Property Patentes() As List(Of BEPatenteBasica)
        Get
            Return _patentes
        End Get
        Set(ByVal Value As List(Of BEPatenteBasica))
            _patentes = Value
        End Set
    End Property

    ''' 
    ''' <param name="codigo"></param>
    Public Overrides Function validar(ByVal codigo As String) As Boolean
        For Each f As BE.BEPatenteBasica In Me.Patentes
            If f.validar(codigo) Then
                Return True
            End If
        Next
        Return False

    End Function


End Class ' BEFamilia
