'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEIdioma.vb
''  Implementation of the Class BEIdioma
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:30:30 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



'Option Explicit On
'Option Strict On


Public Class BEIdioma


    Private _codigo As String
    Private _descripcion As String
    Private _id As Integer
    Private _tags As List(Of BETag)
    Public m_BETag As BETag

    Public Property Codigo() As String
        Get
            Return _codigo
        End Get
        Set(ByVal Value As String)
            _codigo = Value
        End Set
    End Property

    Public Property Descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal Value As Integer)
            _id = Value
        End Set
    End Property

    Public Property Tags() As List(Of BETag)
        Get
            Return _tags
        End Get
        Set(ByVal Value As List(Of BETag))
            _tags = Value
        End Set
    End Property


End Class ' BEIdioma
