'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEPatenteBasica.vb
''  Implementation of the Class BEPatenteBasica
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:30:52 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



'Option Explicit On
'Option Strict On

Public MustInherit Class BEPatenteBasica


    Private _codigo As String
    Private _descripcion As String
    Private _dvh As String
    Private _nativo As Byte

    Public Property Codigo() As String
        Get
            Return _codigo
        End Get
        Set(ByVal Value As String)
            _codigo = Value
        End Set
    End Property

    Public Property Descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Property Dvh() As String
        Get
            Return _dvh
        End Get
        Set(ByVal Value As String)
            _dvh = Value
        End Set
    End Property

    Public Property Nativo() As Byte
        Get
            Return _nativo
        End Get
        Set(ByVal Value As Byte)
            _nativo = Value
        End Set
    End Property

    ''' 
    ''' <param name="codigo"></param>
    Public MustOverride Function validar(ByVal codigo As String) As Boolean


End Class ' BEPatenteBasica
