'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEPermiso.vb
''  Implementation of the Class BEPermiso
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:30:59 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



'Option Explicit On
'Option Strict On



Public Class BEPermiso
    Inherits BEPatenteBasica


    ''' 
    ''' <param name="descripcion">nombre del control a validar</param>
    Public Overrides Function validar(ByVal descripcion As String) As Boolean
        Return (codigo = Me.Descripcion)

    End Function


End Class ' BEPermiso
