'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEReporte.vb
''  Implementation of the Class BEReporte
''  Generated by Enterprise Architect
''  Created on:      06-Jun-2014 11:44:31 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''




Public Class BEReporte


    Private _cuerpo As String
    Private _footer As String
    Private _titulo As String

    Public Property Cuerpo() As String
        Get
            Return _cuerpo
        End Get
        Set(ByVal Value As String)
            _cuerpo = Value
        End Set
    End Property

    Public Property Footer() As String
        Get
            Return _footer
        End Get
        Set(ByVal Value As String)
            _footer = Value
        End Set
    End Property

    Public Sub New()

    End Sub

    Public Property Ttitulo() As String
        Get
            Return _titulo
        End Get
        Set(ByVal Value As String)
            _titulo = Value
        End Set
    End Property


End Class ' BEReporte

