'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEServicioBase.vb
''  Implementation of the Class BEServicioBase
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:47:10 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''




Public MustInherit Class BEServicioBase


    Private _cliente As BECliente
    Private _codigo As String
    Private _descripcion As String
    Private _id As Integer
    Private _precio As Double
    Public m_BECliente As BECliente

    Public Property Cliente() As BECliente
        Get
            Return _cliente
        End Get
        Set(ByVal Value As BECliente)
            _cliente = Value
        End Set
    End Property

    Public Property Codigo() As String
        Get
            Return _codigo
        End Get
        Set(ByVal Value As String)
            _codigo = Value
        End Set
    End Property

    Public Property Descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal Value As Integer)
            _id = Value
        End Set
    End Property

    Public Property Precio() As Double
        Get
            Return _precio
        End Get
        Set(ByVal Value As Double)
            _precio = Value
        End Set
    End Property


End Class ' BEServicioBase
