'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEServicioAdicional.vb
''  Implementation of the Class BEServicioAdicional
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:47:48 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''





Public MustInherit Class BEServicioAdicional
    Inherits BEServicioBase




    Public MustOverride Function isBkp() As Boolean

    Public MustOverride Function isSnap() As Boolean

    

End Class ' BEServicioAdicional
