'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BESnapshot.vb
''  Implementation of the Class BESnapshot
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:47:59 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Public Class BESnapshot
    Inherits BEServicioAdicional


   
    Public Overrides Function isBkp() As Boolean
        isBkp = False
    End Function

    Public Overrides Function isSnap() As Boolean
        isSnap = True
    End Function



End Class ' BESnapshot

