'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BESnapshot.vb
''  Implementation of the Class BESnapshot
''  Generated by Enterprise Architect
''  Created on:      01-Jun-2014 12:47:59 AM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Public Class BESnapshot
    Inherits BEServicioAdicional

    Sub New()
        Id = 5
    End Sub

   
  



End Class ' BESnapshot

