'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BETag.vb
''  Implementation of the Class BETag
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:32:18 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



'Option Explicit On
'Option Strict On


Public Class BETag


    Private _cod_idoma As String
    Private _codigo As String
    Private _leyenda As String

    Public Property Cod_idoma() As String
        Get
            Return _cod_idoma
        End Get
        Set(ByVal Value As String)
            _cod_idoma = Value
        End Set
    End Property

    Public Property Codigo() As String
        Get
            Return _codigo
        End Get
        Set(ByVal Value As String)
            _codigo = Value
        End Set
    End Property

    Public Property Leyenda() As String
        Get
            Return _leyenda
        End Get
        Set(ByVal Value As String)
            _leyenda = Value
        End Set
    End Property


End Class ' BETag
