'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BEUsuario.vb
''  Implementation of the Class BEUsuario
''  Generated by Enterprise Architect
''  Created on:      11-Apr-2014 2:27:24 PM
''  Original author: pepo
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports System.Web.Script.Serialization




<Serializable()> _
Public Class BEUsuario
    Inherits BEUsuarioBase


    Private _apellido As String
    Private _nombre As String


    Public Property Apellido() As String
        Get
            Return _apellido
        End Get
        Set(ByVal Value As String)
            _apellido = Value
        End Set
    End Property

    Public Property Nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property



End Class ' BEUsuario
